name: task_list_application
description: "A mobile Application to manage tasks"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.2        # For state management (MVVM)
  sqflite: ^2.4.1      # SQLite database operations
  path_provider: ^2.1.5    # To locate the database file path

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

# Enable Material design icons for your app.
flutter:
  uses-material-design: true
